name: 'Google Indexing'
description: 'Index your site on Google using the Indexing API.'
author: 'Robin Genz <mail@robingenz.dev>'

# Define your inputs here.
inputs:
  siteUrl: 'bjjroadmaps.com'
    description: 'The domain or site URL of the site to be indexed.'
    required: true
  gcpServiceAccountKey: ${{ secrets.GCP_SA_KEY }}
    description: 'The GCP service account key in JSON format.'
    required: true

runs:
  using: node20
  main: dist/index.mjs
